version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: url-shortener-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: url-shortener-redis

    restart: always

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
